# Conda environment configuration for the PROAKTIV project
# To create the environment, run:
# conda env create -f environment.yml
# To activate the environment, run:
# conda activate proaktiv

name: proaktiv

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # --- Core ---
  - python=3.9

  # --- PyTorch Stack (with GPU support) ---
  - pytorch::pytorch=2.1.1
  - pytorch::pytorch-cuda=11.8 # Matches the PyTorch build
  - pytorch::torchaudio
  - pytorch::torchvision

  # --- Data Science & ML ---
  - pandas=2.1.4
  - numpy=1.26.2
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - matplotlib=3.8.2
  - seaborn=0.13.0

  # --- Bioinformatics & Cheminformatics ---
  - deepchem=2.7.1
  - lifelines=0.27.8
  
  # --- Utility & Frameworks ---
  - optuna=3.4.0
  - tabulate=0.9.0
  - tqdm=4.66.1
  - requests=2.31.0
  - openpyxl=3.1.2
  
  # --- Notebook Environment ---
  - ipython=8.17.2
  - jupyter=1.0.0
  
  # --- Pip dependencies (for packages not easily available on conda) ---
  - pip:
    - DeepPurpose==0.1.6
    - transformers==4.35.2
